# De-identification Rules

# PHI Elements to Remove
phi_elements:
  - patient_name
  - medical_record_number
  - address
  - phone_number
  - email
  - social_security_number
  - account_number
  - health_plan_beneficiary_number
  - device_identifiers
  - biometric_identifiers
  - full_face_photos
  - any_other_unique_identifying_number

# Date Shifting
date_shifting:
  enabled: true
  shift_range_days: [-365, 365]
  consistent_per_patient: true
  preserve_day_of_week: true

# Age Handling
age_handling:
  truncate_ages_over_89: true
  bin_size_for_elderly: 5

# Geographic Data
geographic_data:
  minimum_granularity: state
  zip_code_handling: first_3_digits

# Quasi-identifiers
quasi_identifiers:
  - race
  - ethnicity
  - gender
  - rare_disease_codes
  - occupation

# Audit Logging
audit:
  log_all_access: true
  log_all_transformations: true
  retention_period_days: 365
